<?php 
$firstname != '' && $email != '' && $password != '' 
//&& $abenteuer_01 != '' && $abenteuer_02 != '' && $abenteuer_03 != '' 
//&& $aesthetik_01 != '' && $aesthetik_02 != '' && $aesthetik_03 != '' 
//&& $aktiv_01 != '' && $aktiv_02 != '' && $aktiv_03 != '' 
//&& $altruismus_01 != '' && $altruismus_02 != '' && $altruismus_03 != '' 
//&& $angst_01 != '' && $angst_02 != '' && $angst_03 != '' 
&& $befang_01 != '' //&& $befang_02 != '' && $befang_03 != '' 
//&& $bescheiden_01 != '' && $bescheiden_02 != '' && $bescheiden_03 != '' 
//&& $disziplin_01 != '' && $disziplin_02 != '' && $disziplin_03 != '' 
//&& $durchsetz_01 != '' && $durchsetz_02 != '' && $durchsetz_03 != '' 
//&& $emotion_01 != '' && $emotion_02 != '' && $emotion_03 != '' 
//&& $entgegen_01 != '' && $entgegen_02 != '' && $entgegen_03 != '' 
//&& $fantasie_01 != '' && $fantasie_02 != '' && $fantasie_03 != '' 
//&& $freimut_01 != '' && $freimut_02 != '' && $freimut_03 != '' 
//&& $gesell_01 != '' && $gesell_02 != '' && $gesell_03 != '' 
//&& $glueck_01 != '' && $glueck_02 != '' && $glueck_03 != '' 
//&& $herzlich_01 != '' && $herzlich_02 != '' && $herzlich_03 != '' 
//&& $impuls_01 != '' && $impuls_02 != '' && $impuls_03 != '' 
//&& $intellekt_01 != '' && $intellekt_02 != '' && $intellekt_03 != '' 
//&& $kompetenz_01 != '' && $kompetenz_02 != '' && $kompetenz_03 != '' 
//&& $leistung_01 != '' && $leistung_02 != '' && $leistung_03 != '' 
//&& $liberal_01 != '' && $liberal_02 != '' && $liberal_03 != '' 
//&& $mitgefuehl_01 != '' 
&& $mitgefuehl_02 != '' //&& $mitgefuehl_03 != '' 
//&& $neugier_01 != '' && $neugier_02 != '' && $neugier_03 != '' 
//&& $ordnung_01 != '' && $ordnung_02 != '' && $ordnung_03 != '' 
//&& $pessi_01 != '' && $pessi_02 != '' && $pessi_03 != '' 
//&& $pflicht_01 != '' && $pflicht_02 != '' && $pflicht_03 != '' 
//&& $reizbar_01 != '' && $reizbar_02 != '' && $reizbar_03 != '' 
//&& $sorgfalt_01 != '' && $sorgfalt_02 != '' && $sorgfalt_03 != '' 
//&& $verletz_01 != '' && $verletz_02 != '' && $verletz_03 != '' 
//&& $vertrauen_01 != '' && $vertrauen_02 != '' && $vertrauen_03 != ''

?>