USE GSMAND2

UPDATE ARTIKEL
SET BESTNR = A1_ImportArtikel.BESTNR,
    ZUSTEXT1 = A1_ImportArtikel.ZUSTEXT1    
FROM A1_ImportArtikel
WHERE ARTIKEL.ARTNR = A1_ImportArtikel.ARTNR




UPDATE VKPREIS
SET ABMENGE = 99
FROM A1_ImportArtikel JOIN ARTIKEL ON A1_ImportArtikel.ARTNR = ARTIKEL.ARTNR
WHERE  VKPREIS.ARTINR = ARTIKEL.NUMMER






